### ISSUE TITLE
Crash in Nuxt 3.8

### ISSUE THREAD

**Issue by IlyaSemenov** [bartdominiak/vue-snap#86]
Importing vue-snap in a Nuxt page crashes with:

```
[Vue Router warn]: uncaught error during route navigation:
/xxx/node_modules/.pnpm/seamless-scroll-polyfill@1.2.4/node_modules/seamless-scroll-polyfill/dist/esm/Element.scrollBy.js:1
import { isObject, isScrollBehaviorSupported, modifyPrototypes, nonFinite, } from "./common.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1153:20)
    at Module._compile (node:internal/modules/cjs/loader:1197:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at /xxx/node_modules/.pnpm/vue-snap@0.7.1_vue@3.3.8/node_modules/vue-snap/dist/vue-snap.umd.js:1:79
    at Object.<anonymous> (/xxx/node_modules/.pnpm/vue-snap@0.7.1_vue@3.3.8/node_modules/vue-snap/dist/vue-snap.umd.js:1:400)
```

**Comment by vityapro** [comment]
The main issue is in `lodash` lib. You can replace the whole lib with a simple function in the utils file:
`export function debounce(fn, wait){
    let timer;
   return function(...args){
     if(timer) {
        clearTimeout(timer); // clear any pre-existing timer
     }
     const context = this; // get the current context
     timer = setTimeout(()=>{
        fn.apply(context, args); // call the function if time expires
     }, wait);
   }
}`
